### ISSUE TITLE
gee_tools: Interactive Maps with Two Options

### ISSUE THREAD

**Issue by lieying2016** [gee-community/gee_tools#11]
Option 1: maptool
============================================
I followed the code in your notebook.

``` python
col = ee.ImageCollection('COPERNICUS/S2')
site = ee.Geometry.Point([-72,-42])
col = col.filterBounds(site).filterMetadata('CLOUD_COVERAGE_ASSESSMENT','less_than',40)
image =ee.Image(col.first()) 

geom = image.geometry()
visParam = {'bands':['B8','B11','B4'], 'min':0,'max':5000}
# addLayer has a parameter called inspect
inspect = {'data':image,'reducer':'mean'}
from geetools import maptool
Map = maptool.Map()
Map.addLayer(image,visParam,'Sentinel 2')
Map.centerObject(image)
Map.addLayer(geom, name = 'Image Boundary',inspect = inspect)
Map.show()
```
> AttributeError: 'dict' object has no attribute 'iteritems'

Option 2: ipymap
===========================================

``` python
from geetools import ipymap
Map2 = ipymap.Map()
Map2.show()
```
> C:\ProgramData\Anaconda3\lib\site-packages\geetools\ipymap.py in <module>()
>      18                      get_image_tile, get_geojson_tile, get_bounds, get_zoom,\
>      19                      create_html, feature_properties_output
>  ---> 20 import maptool
>      21 from . import ipytools
>      22 import threading
> 
> ModuleNotFoundError: No module named 'maptool'

**Comment by fitoprincipe** [comment]
Hi @lieying2016, both errors are due to python 3, because I used python 2 at first, but I am doing the migration, so it's good to know. I have already fixed the last error. I will correct the first one right away. Thanks.

**Comment by fitoprincipe** [comment]
Fixed

**Comment by lieying2016** [comment]
Thank you!
It seems that I still have the same errors. Could you tell me what I should do to get rid of these errors? I just update the gee_tools package using Conda.

**Comment by fitoprincipe** [comment]
Hi @lieying2016, You have to do the following:

- download and install [git for windows](https://git-scm.com/download/win) (if you don't have it already)
- clone the repo:
    1. go to Anaconda prompt
    2. navigate to the folder where you want to hold the repo
    3. write:
        - > git clone https://www.github.com/gee-community/gee_tools
- activate your environment (if necessary)
    suppose your environment is gee:
    > activate gee
- navigate into the repo:
    > cd gee_tools
- placed inside `gee_tools` folder write:
    > pip install --upgrade .
    - (don't omit the last point, which means: *the package in **this** folder*)

This will install repo's `gee_tools` into the activated environment

**Comment by lieying2016** [comment]
Thank you @fitoprincipe. I will do it.

**Comment by lieying2016** [comment]
Hi @fitoprincipe , I just followed your suggestions. 

There are still problems. I think I have clone the gee_tools correctly because Anaconda prompt said: 
 Successfully built geetools
Installing collected packages: geetools
    Found existing installation: geetools 0.0.16
       Uninstalling geetools-0.0.16:
             Successfully uninstalled geetools-0.0.16
Successfully installed geetools-0.0.16

The new problems for option 1 (maptool) is the same:
AttributeError: 'dict' object has no attribute 'iteritems'

The problem for option 2 (ipymap) is:
AttributeError: module 'geetools.ipytools' has no attribute 'RealBox'

I have no idea where I was wrong.

**Comment by fitoprincipe** [comment]
Mmm.. that is rare, I changed all `iteritems` for `items`, see this commit: https://github.com/gee-community/gee_tools/commit/c128f0fa4b79323a23559a9f45963b95cad411b3

**Comment by fitoprincipe** [comment]
Hi @lieying2016, I just uploaded a new version 0.1.0, you can check it out!

**Comment by lieying2016** [comment]
Thank you @fitoprincipe .  I tried the geetools again. 

It seems that you took out the tools.col2drive function.

For showing maps, the first option (maptool) has no error now. But the result is blank when I call Map.show(). Below is the code:
===============================================================
from geetools.ui import maptool
Map = maptool.Map()
Map.addLayer(image,visParam,'Sentinel 2')
Map.centerObject(image)
Map.addLayer(geom, name = 'Image Boundary',inspect = inspect)
Map.show()
===============================================================
The second option (ui) has an error. See the code below:
===============================================================
TraitError                                Traceback (most recent call last)
<ipython-input-12-ff7ff8cdfb11> in <module>()
      1 # Method 2 plot image using ipymap
      2 from geetools import ui
----> 3 Map2 = ui.Map()
      4 Map2.show()

.......

TraitError: The 'children' trait of a Tab instance must be a tuple, but a value of class 'odict_values' (i.e. odict_values([CustomInspector(children=(SelectMultiple(options=(), value=()), Accordion(selected_index=None)))])) was specified.
===============================================================

**Comment by fitoprincipe** [comment]
Sorry, I made some major changes (that's why the change of version) but functions are still there. 

Map's modules are under `ui` now:

    from geetools import ui
    Map = ui.ipymap.Map()

and `col2drive` is now:

    from geetools import batch
    batch.ImageCollection.toDrive()

I did not get that `TraitError` when I made my tests. I'll check it out. 
Thank you!

**Comment by fitoprincipe** [comment]
commit https://github.com/gee-community/gee_tools/commit/a1e97b4476ca3e2f4f4acf9e815bcf437dc72e58 should fix it. Can you test it?

**Comment by lieying2016** [comment]
Hi @fitoprincipe , I just tried the geetools again.

1. Map's modules:
#Option 1 ( maptool): The result is still blank.
================================================================= 
from geetools.ui import maptool
Map = maptool.Map()
Map.addLayer(image,visParam,'Sentinel 2')
Map.centerObject(image)
Map.addLayer(geom, name = 'Image Boundary',inspect = inspect)
Map.show()
=================================================================
# Option 2 (ui)
Although I have added tuple as you suggested, the error still exists.

=================================================================
TraitError                                Traceback (most recent call last)
<ipython-input-21-ff7ff8cdfb11> in <module>()
      1 # Method 2 plot image using ipymap
      2 from geetools import ui
----> 3 Map2 = ui.Map()
      4 Map2.show()

C:\ProgramData\Anaconda3\lib\site-packages\geetools\ui\ipymap.py in __init__(self, tabs, **kwargs)
     89                     widget = widgets[tab]
     90                     handler = handlers[tab]
---> 91                     self.addTab(tab, handler, widget)
     92                 else:
     93                     raise ValueError('Tab {} is not recognized. Choose one of {}'.format(tab, widgets.keys()))

C:\ProgramData\Anaconda3\lib\site-packages\geetools\ui\ipymap.py in addTab(self, name, handler, widget)
    688 
    689             # Update tab children
--> 690             self._update_tab_children()
    691         else:
    692             print('Tab {} already exists, please choose another name'.format(name))

C:\ProgramData\Anaconda3\lib\site-packages\geetools\ui\ipymap.py in _update_tab_children(self)
    636         """ Update Tab children from tab_children_dict """
    637         # Set tab_widget children
--> 638         _### self.tab_widget.children = tuple(self.tab_children_dict.values())_
    639         # Set tab_widget names
    640         for i, name in enumerate(self.tab_children_dict.keys()):

C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py in __set__(self, obj, value)
    583             raise TraitError('The "%s" trait is read-only.' % self.name)
    584         else:
--> 585             self.set(obj, value)
    586 
    587     def _validate(self, obj, value):

C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py in set(self, obj, value)
    557 
    558     def set(self, obj, value):
--> 559         new_value = self._validate(obj, value)
    560         try:
    561             old_value = obj._trait_values[self.name]

C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py in _validate(self, obj, value)
    589             return value
    590         if hasattr(self, 'validate'):
--> 591             value = self.validate(obj, value)
    592         if obj._cross_validation_lock is False:
    593             value = self._cross_validate(obj, value)

C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py in validate(self, obj, value)
   2236         if isinstance(value, self._cast_types):
   2237             value = self.klass(value)
-> 2238         value = super(Container, self).validate(obj, value)
   2239         if value is None:
   2240             return value

C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py in validate(self, obj, value)
   1675             return value
   1676         else:
-> 1677             self.error(obj, value)
   1678 
   1679     def info(self):

C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py in error(self, obj, value)
   1522                 % (self.name, self.info(), msg)
   1523 
-> 1524         raise TraitError(e)
   1525 
   1526 

TraitError: The 'children' trait of a Tab instance must be a tuple, but a value of class 'odict_values' (i.e. odict_values([CustomInspector(children=(SelectMultiple(options=(), value=()), Accordion(selected_index=None)))])) was specified.



2.  batch.ImageCollection.toDrive():  Another error appears!

===================================================================
from geetools import batch
tasks = batch.ImageCollection.toDrive(ndvi_mon,'NDVI0607',scale=1000,dataType='float',region=watershed)

AttributeError                            Traceback (most recent call last)
<ipython-input-9-8bdd11105595> in <module>()
      7 # print(task_id)
      8 # export image collection to drive
----> 9 tasks = batch.ImageCollection.toDrive(ndvi_mon,'NDVI0607',scale=1000,dataType='float',region=watershed)
     10 task_id = task.id
     11 print(task_id)

C:\ProgramData\Anaconda3\lib\site-packages\geetools\batch.py in toDrive(col, folder, scale, dataType, region, **kwargs)
    401             region = ee.Image(alist.get(0)).geometry().getInfo()["coordinates"]
    402         else:
--> 403             region = tools.getRegion(region)
    404 
    405         for idx in range(0, size):

AttributeError: module 'geetools.tools' has no attribute 'getRegion'
==================================================================

**Comment by fitoprincipe** [comment]
Ok, the last error is my fault. I didn't make a test for batch.py (I will soon). Corrected in https://github.com/gee-community/gee_tools/commit/1d2e7e75bd87eae80bc634945a2c7bfbd104b782. But the first and second issues I can't reproduce. On Monday at the office I will check it again, but it was working fine in both python 2 and python 3

**Comment by fitoprincipe** [comment]
Hello @lieying2016 , today I have encounter the same issue 

    TraitError: The 'children' trait of a Tab instance must be a tuple, but a value of class 'odict_values' (i.e. 
    odict_values([CustomInspector(children=(SelectMultiple(options=(), value=()), 
    Accordion(selected_index=None)))])) was specified.

before pulling the fix (version 0.1.1). But after pulling it (and installing it) the issue was solved. It should be solved for you too.

**Comment by fitoprincipe** [comment]
closing by now, will reopen if needed
