### ISSUE TITLE
Issues when using geetools to download imagecollection

### ISSUE THREAD

**Issue by lieying2016** [gee-community/gee_tools#9]
https://gis.stackexchange.com/questions/279412/exporting-large-number-of-landsat-images-from-google-earth-engine
I followed your answer to this issue(downloading imageCollection from GEE), but I got another problem. Here is my code:
==================================================================================
# download the data

ndvi = ee.ImageCollection('MODIS/006/MOD13A2').filterDate('2009-01-01','2017-12-31').select('NDVI')

ndvi_mon = ndvi.filter(ee.Filter.calendarRange(2009,2017,'year')).filter(ee.Filter.calendarRange(6,7,'month'))

from geetools import tools

# download  image

tasks = tools.col2drive(ndvi_mon, 'NDVI0607', scale=1000)

try n° 0 ERROR: name 'TYPES' is not defined
try n° 1 ERROR: name 'TYPES' is not defined
try n° 2 ERROR: name 'TYPES' is not defined
try n° 3 ERROR: name 'TYPES' is not defined
try n° 4 ERROR: name 'TYPES' is not defined

Even though I added (dataType='float'), it is still the same error.

**Comment by lieying2016** [comment]
Update:  I can download images using the function: ee.batch.Export.image.toDrive, but not the tools.col2drive. The tools.col2drive function still has error "try n° 0 ERROR: name 'TYPES' is not defined".

**Comment by fitoprincipe** [comment]
Hi @lieying2016 , I have fixed it. Didn't package it, but you can install it from the repository, if you don't know how to do it, let me know and I walk you through.

**Comment by lieying2016** [comment]
Thanks for letting me know!
I just updated my gee_tools package, but the same error still exists. Should I wait for a while?

**Comment by fitoprincipe** [comment]
Hi @lieying2016! Sorry about the delay.. you may have solved the issue already, but just to let you know, I have tested it in the new version, and works fine

``` python
from geetools import batch
tasks = batch.ImageCollection.toDrive(ndvi_mon, 'NDVI0607', scale=1000, maxPixels=1e13)
```

**Comment by lieying2016** [comment]
Thanks for letting me know.

It has already worked for me!

Best

**Comment by fitoprincipe** [comment]
great! cheers
